model:
  descriptor:
    axis_neuron: 16
    neuron: [25, 50, 100]
    rcut: 6.5
    rcut_smth: 4.5
    resnet_dt: true
    seed: 1
    sel: [128, 256, 128]
    type: se_a
  fitting_net:
    neuron: [240, 120, 60, 30, 15]
    resnet_dt: true
    seed: 1
  type_map: [Al, O, H]
learning_rate:
  decay_steps: 5000
  start_lr: 5.00e-04
  stop_lr:  1.00e-08
  type: exp
loss:
  start_pref_e: 0.2
  limit_pref_e: 1.0
  start_pref_f: 1000.0
  limit_pref_f: 1.0
  start_pref_v: 0.0
  limit_pref_v: 0.0
training:
  batch_size: 1
  disp_file: lcurve.out
  disp_freq: 100
  disp_training: true
  load_ckpt: model.ckpt
  numb_test: 10
  profiling: false
  profiling_file: timeline.json
  save_ckpt: model.ckpt
  save_freq: 1000
  seed: 1
  set_prefix: set
  stop_batch: 200000
  systems: []
  time_training: true
