name: Test workflow scripts

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup conda environments
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: envs/mphys.yml
          environment-name: mphys
          cache-env: true
          
      - name: Show micromamba info
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list
          pip -V
      
      - name: Test scripts
        shell: bash -l {0}
        run: |
          pytest project/tests --junit-xml pytest.xml --cov=project/scripts --cov-report=xml
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "pytest.xml"
      
      - name: Publish coverage result
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: "coverage.xml"
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

